config/routes.rb
Rails.application.routes.draw do
  resources :participants
  resources :interviews

  # SPA ROUTES
  get '/home' => 'interviews#home'
  # get '/interviews/new' => 'interviews#new'
  # get '/interviews/:id' => 'interviews#show'

  # REACT ROUTES
  match '*path', to: 'interviews#index', via: :all

  root "interviews#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interview.rb
class Interview < ApplicationRecord
  has_many :interview_participants,dependent: :destroy
  has_many :participants, through: :interview_participants

  def self.checkClash(participant, interview_params)
    prevInterviews = participant.interviews
    prevInterviews.each do |prevInterview|
      prevStart = prevInterview.start
      prevEnd = prevInterview.end
      curStart = Time.parse(interview_params[:start]).getutc
      curEnd = Time.parse(interview_params[:end]).getutc
      unless ((prevStart > curEnd) or (curStart > prevEnd))
        # clashOccured
        return true  
      end
    end
    return false
  end

  def self.clash(interview_params, emails)
    # check clash for each participant
    all_emails = emails.split(",")
    all_emails.each do |email|
      participant = Participant.where(email: email).first
      if participant.nil?
        puts("New Participant")
      elsif (checkClash(participant, interview_params))
        # clashOccured
        return true
      end
    end
    return false
  end

end

app/models/interview_participant.rb
class InterviewParticipant < ApplicationRecord
  belongs_to :interview
  belongs_to :participant

  enum position: {interviewer: 0, interviewee: 1}
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_one_attached :resume
  has_many :interview_participants,dependent: :destroy
  has_many :interviews, through: :interview_participants

  def serialize
    return self.attributes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  def index
  end
  
  def home
    @interviews = Interview.all
    render json: @interviews
  end

  def show
    @participants = @interview.participants
    render :json => {
      interview: @interview,
      participants: @participants.map{|p| p.serialize}
    }
  end

  def new
    @interview = Interview.new
  end

  def edit
  end

  def create
    if (Interview.clash(interview_params, interview_params[:pemail]))
      respond_to do |format|
        format.html { redirect_to interviews_path, notice: 'Couldn,t create interview because of clash.' }
      end
    else
      @interview = Interview.new
      emails = interview_params[:pemail]
      allEmails = emails.split(",")
      roles = interview_params[:position]
      allRoles = roles.split(",")
      @interview = Interview.create(:start => interview_params[:start], :end => interview_params[:end], :title => interview_params[:title])

      allEmails.zip(allRoles).each do |email, role|
        # link participant and email for every interview
        curParticipant = Participant.find_or_create_by(email: email)
        @interviewParticipants = InterviewParticipant.create(:interview=> @interview, :participant => curParticipant, :position => role)
        # for testing
        # InterviewMailer.reminder_mail(@interview, email).deliver_now
        # InterviewMailer.reminder_mail(@interview).deliver_later(wait_until: @interview.start - 30.minutes)
      end

      respond_to do |format|
        if @interview.save
          format.html { redirecwst_to @interview, notice: 'Interview was successfully created.' }
          format.json { render :show, status: :created, location: @interview }
        else
          # format.html { render :new }
          format.json { render json: @interview.errors, status: :unprocessable_entity }
        end
      end
    render json: @interview
    end
  end

  def update
    prevInterview = @interview
    @interview.update(:start => interview_params[:start], :end => interview_params[:end], :title => interview_params[:title])
    emails = interview_params[:pemail]
    allEmails = emails.split(",")
    allEmails.each do |email|
      # delete previous job
      DeleteInterviewMailJob.perform_now(prevInterview.id)
      # create new job
      InterviewMailer.updation_mail(@interview, email).deliver_now
      InterviewMailer.reminder_mail(@interview).deliver_later(wait_until: @interview.start - 30.minutes)
    end
    
    render json: @interview
  end

  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url, notice: 'Interview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_interview
      @interview = Interview.find(params[:id])
    end

    def interview_params
      params.require(:interview).permit(:date, :start, :end, :title, :pemail, :position)
    end

    # refer to model
    def set_participant
      @participants = @interview.participants
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  def index
    @participants = Participant.all
  end

  def show
  end

  def new
    @participant = Participant.new
  end

  def edit
  end

  def create
    @participant = Participant.create(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_participant
      @participant = Participant.find(params[:id])
    end

    def participant_params
      params.require(:participant).permit(:email, :resume)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/interviews/_form.html.erb
<%= form_with(model: interview, local: true) do |form| %>
<% if interview.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

  <ul>
    <% interview.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :start %>
  <%= form.datetime_field :start %>
</div>

<div class="field">
  <%= form.label :end %>
  <%= form.datetime_field :end %>
</div>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%=form.label :pemail, "Email of Participants (Comma Separated)" %>
  <%= form.text_field :pemail %>
</div>

<div class="field">
  <%=form.label :position, "Define Role (Comma Separated)" %>
  <%= form.text_field :position %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/interviews/edit.html.erb
<h1>Editing Interview</h1>

<%= render 'form', interview: @interview %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<div id="page_container" class="container pageEntry">
  <article>Loading...</article>
</div>

app/views/interviews/new.html.erb
<h1>New Interview</h1>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @interview.title %>
</p>

<p>
  <strong>Start:</strong>
  <%= @interview.start %>
</p>
<p>
  <strong>End:</strong>
  <%= @interview.end %>
</p>

<div>
  <strong>Participant's Email</strong>
  <% @interview.participants.each do |p| %>
  <p>
    <%= p.email %> || 
    <% curPosition = InterviewParticipant.where(interview_id: @interview.id, participant_id: p.id)%>
    <%= curPosition[0].position %>
    <%if curPosition[0].interviewee? %>
      <% if p.resume.attached? %>
        || <%= link_to 'Download', p.resume, download: '' %>
      <%else%>
        || No Resume Provided
      <%end%>
    <%end%>
  </p>
  <%end%>
</div>

<%= link_to 'Edit', edit_interview_path(@interview) %> |
<%= link_to 'Back', interviews_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>InterviewAppErb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'index' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/participants/_form.html.erb
<%= form_with(model: participant, local: true) do |form| %>
<% if participant.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

  <ul>
    <% participant.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :email %>
  <%= form.text_field :email %>
</div>

<div class="field">
  <%= form.label :resume %>
  <%= form.file_field :resume %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
    <tr>
      <td><%= participant.email %></td>
      <td>
        <% if participant.resume.attached? %>
          <%= link_to 'Download', participant.resume, download: '' %>
        <%else%>
          No Resume Provided
        <%end%>
      </td>
      <td><%= link_to 'Show', participant %></td>
      <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
      <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<p>
  <strong>Resume:</strong>
  <% if @participant.resume.attached? %>
    <%= link_to 'Download', @participant.resume, download: '' %>
  <%else%>
    No Resume Provided
  <%end%>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>